### ISSUE TITLE
How to set this up?

### ISSUE THREAD

**Issue by Y2K-x** [yellows8/wiiuhaxx_common#3]

**Comment by Y2K-x** [comment]
Sorry bout that, hit Enter too early.

Anyway, I'm having a lot of issues setting this up, and since I can't find any tutorial, I though i could ask the dev himself how it works. Thanks.

**Comment by Y2K-x** [comment]
Might I add I don't know a lot about PHP, so some help trying to understand this would be nice.

**Comment by bhcoder** [comment]
http://05sonicblue.com/wiiuhax/

**Comment by Y2K-x** [comment]
So all I have to do is drag and drop them into my web server? Cool, thanks.
